//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackDesertLogin.Configurations {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ServicesConfigs : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServicesConfigs defaultInstance = ((ServicesConfigs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServicesConfigs())));
        
        public static ServicesConfigs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string LauncherService_ip {
            get {
                return ((string)(this["LauncherService_ip"]));
            }
            set {
                this["LauncherService_ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6667")]
        public int LauncherService_port {
            get {
                return ((int)(this["LauncherService_port"]));
            }
            set {
                this["LauncherService_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6668")]
        public int GameServicePort {
            get {
                return ((int)(this["GameServicePort"]));
            }
            set {
                this["GameServicePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string GameServiceIp {
            get {
                return ((string)(this["GameServiceIp"]));
            }
            set {
                this["GameServiceIp"] = value;
            }
        }
    }
}
